dbt_snowflake_supermarket:
  outputs:
    dev:
      type: snowflake
      account: hn41669.ap-southeast-1
      user: demo_user
      password: Demo1234.
      role: ACCOUNTADMIN
      database: DBT_SUPERMARKET
      warehouse: DEMO_DWH
      schema: PUBLIC
      # private_key_passphrase: "{{ env_var('SNOWFLAKE_DBT_KEY_PASSPHRASE') }}"
      # private_key_path: "{{ env_var('SNOWFLAKE_DBT_KEY_PATH') }}"
      threads: 1
  target: dev