version: 2

models:
  - name: stg_customers
    description: "Staging table for customers data"
    columns:
      - name: customer_id
        # description: "Unique ID of the customer"
        tests:
          - unique
          - not_null
      - name: full_name
        description: ""
        tests:
          - not_null
      - name: email
        description: "Customer's email address"
        tests:
          - not_null
      - name: phone_number
        description: "Customer's phone number"
        tests:
          - not_null
      - name: registered_at
        description: "Date the customer was registered"
        tests:
          - not_null

  - name: stg_products
    description: "Staging table for products data"
    columns:
      - name: product_id
        description: "Unique ID of the product"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      - name: category
        description: "Category of the product"
        tests:
          - not_null
      - name: price
        description: "Price of the product"
        tests:
          - not_null

  - name: stg_stores
    description: "Staging table for stores data"
    columns:
      - name: store_id
        description: "Unique ID of the store"
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Name of the store"
        tests:
          - not_null
      - name: location
        description: "Location of the store"
        tests:
          - not_null

  - name: stg_transactions
    description: "Staging table for transactions data"
    columns:
      - name: transaction_id
        description: "Unique ID of the transaction"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID of the customer who made the transaction"
        tests:
          - not_null
      - name: product_id
        description: "ID of the product involved in the transaction"
        tests:
          - not_null
      - name: store_id
        description: "ID of the store where the transaction happened"
        tests:
          - not_null
      - name: quantity
        description: "Quantity of products bought in the transaction"
        tests:
          - not_null
      - name: transaction_date
        description: "Date of the transaction"
        tests:
          - not_null

  - name: customer_order_summary
    description: "Summary of customer orders including total items bought and total transactions"
    data_tests:
      - test_customer_order_summary
    columns:
      - name: customer_id
        description: "Unique ID of the customer"
        tests:
          - unique
          - not_null
      - name: full_name
        description: "Full name of the customer"
        tests:
          - not_null
      - name: email
        description: "Customer's email address"
        tests:
          - not_null
      - name: phone_number
        description: "Customer's phone number"
        tests:
          - not_null
      - name: registered_at
        description: "Date the customer was registered"
        tests:
          - not_null
      - name: total_items_bought
        description: "Total number of items bought by the customer"
        tests:
          - not_null
      - name: total_transactions
        description: "Total number of transactions made by the customer"
        tests:
          - not_null
      - name: total_spent
        description: "Total amount spent by the customer"
        tests:
          - not_null

  - name: store_sales_summary
    description: "Summary of sales per store"
    columns:
      - name: store_id
        description: "Unique ID of the store"
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Name of the store"
        tests:
          - not_null
      # - name: total_items_sold
      #   description: "Total number of items sold in the store"
      #   tests:
      #     - not_null
      # - name: total_transactions
      #   description: "Total number of transactions in the store"
      #   tests:
      #     - not_null
      # - name: total_revenue
      #   description: "Total revenue generated by the store"
      #   tests:
      #     - not_null
